version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_DB=judge0
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2358:2358
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:
